monitor_financial_news:
  # ...existing code...
  parameters:
    max_news_age_hours: 24
    min_confidence_score: 0.8
    priority_sources:
      - Reuters
      - Bloomberg
      - Financial Times
    excluded_sources:
      - social_media
      - blogs

analyze_market_data:
  # ...existing code...
  parameters:
    data_points_required:
      - price_trends
      - volume_analysis
      - market_sentiment
      - economic_indicators
    time_range_days: 90
    confidence_threshold: 0.85

# ...existing code...
