name: CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest mypy black flake8 pytest-cov
    - name: Run linting
      run: |
        flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203
    - name: Check formatting
      run: |
        black --check src/ tests/
    - name: Check types
      run: |
        mypy src/ tests/ --ignore-missing-imports --strict
    - name: Run tests with coverage
      run: |
        pytest tests/ --cov=src/ --cov-report=xml
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
